package poc.database.core.models;
// Generated Aug 6, 2020, 8:53:46 PM by Hibernate Tools 5.2.0.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Cycles generated by hbm2java
 */
@Entity
@Table(name="CYCLES"
    ,schema="HIT_RESYNTHESIS"
)
public class Cycles  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal version;
     private Workflows workflows;
     private Serializable createdAt;
     private BigDecimal createdBy;
     private Serializable updatedAt;
     private BigDecimal updatedBy;
     private Clob description;
     private Boolean isCompleted;
     private String name;
     private Long position;
     private Long stepCount;

    public Cycles() {
    }

	
    public Cycles(BigDecimal id) {
        this.id = id;
    }
    public Cycles(BigDecimal id, Workflows workflows, Serializable createdAt, BigDecimal createdBy, Serializable updatedAt, BigDecimal updatedBy, Clob description, Boolean isCompleted, String name, Long position, Long stepCount) {
       this.id = id;
       this.workflows = workflows;
       this.createdAt = createdAt;
       this.createdBy = createdBy;
       this.updatedAt = updatedAt;
       this.updatedBy = updatedBy;
       this.description = description;
       this.isCompleted = isCompleted;
       this.name = name;
       this.position = position;
       this.stepCount = stepCount;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Version
    @Column(name="VERSION", scale=0)
    public BigDecimal getVersion() {
        return this.version;
    }
    
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WORKFLOW_ID")
    public Workflows getWorkflows() {
        return this.workflows;
    }
    
    public void setWorkflows(Workflows workflows) {
        this.workflows = workflows;
    }

    
    @Column(name="CREATED_AT")
    public Serializable getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Serializable createdAt) {
        this.createdAt = createdAt;
    }

    
    @Column(name="CREATED_BY", scale=0)
    public BigDecimal getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(BigDecimal createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="UPDATED_AT")
    public Serializable getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Serializable updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="UPDATED_BY", scale=0)
    public BigDecimal getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(BigDecimal updatedBy) {
        this.updatedBy = updatedBy;
    }

    
    @Column(name="DESCRIPTION")
    public Clob getDescription() {
        return this.description;
    }
    
    public void setDescription(Clob description) {
        this.description = description;
    }

    
    @Column(name="IS_COMPLETED", precision=1, scale=0)
    public Boolean getIsCompleted() {
        return this.isCompleted;
    }
    
    public void setIsCompleted(Boolean isCompleted) {
        this.isCompleted = isCompleted;
    }

    
    @Column(name="NAME", length=1020)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="POSITION", precision=10, scale=0)
    public Long getPosition() {
        return this.position;
    }
    
    public void setPosition(Long position) {
        this.position = position;
    }

    
    @Column(name="STEP_COUNT", precision=10, scale=0)
    public Long getStepCount() {
        return this.stepCount;
    }
    
    public void setStepCount(Long stepCount) {
        this.stepCount = stepCount;
    }




}


