package poc.database.core.models;
// Generated Aug 6, 2020, 5:30:42 PM by Hibernate Tools 5.2.0.Final


import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SearchQuery generated by hbm2java
 */
@Entity
@Table(name="SEARCH_QUERY"
    ,schema="HIT_RESYNTHESIS"
)
public class SearchQuery  implements java.io.Serializable {


     private BigDecimal id;
     private BigDecimal createdBy;
     private BigDecimal updatedBy;
     private String module;
     private String name;
     private String queries;

    public SearchQuery() {
    }

	
    public SearchQuery(BigDecimal id) {
        this.id = id;
    }
    public SearchQuery(BigDecimal id, Serializable createdAt, BigDecimal createdBy, Serializable updatedAt, BigDecimal updatedBy, String module, String name, String queries) {
       this.id = id;
       this.createdBy = createdBy;
       this.updatedBy = updatedBy;
       this.module = module;
       this.name = name;
       this.queries = queries;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Column(name="CREATED_BY", scale=0)
    public BigDecimal getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(BigDecimal createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="UPDATED_BY", scale=0)
    public BigDecimal getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(BigDecimal updatedBy) {
        this.updatedBy = updatedBy;
    }

    
    @Column(name="MODULE", length=1020)
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }

    
    @Column(name="NAME", length=1020)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="QUERIES", length=1020)
    public String getQueries() {
        return this.queries;
    }
    
    public void setQueries(String queries) {
        this.queries = queries;
    }




}


